# ***THEME: AGRICULTURE AND FOOD TECHNOLOGY***


### **PROBLEM STATEMENT:**

*Many farmers still rely on middlemen to sell their produce, losing a major share of their income. They lack a simple and transparent way to connect directly with buyers, limiting fair pricing and market access*


**DESCRIPTION:**

*Farmers often face challenges in accessing markets, leading to lower income due to middlemen. This gap restricts their ability to sell produce at fair prices.Create a mobile application that connects farmers directly with consumers and retailers. The app should include features for listing produce, negotiating prices, and managing transactions, thereby reducing dependence on intermediaries*

#### *Prototype built-up by Deepak Kaura (Team Lead of AI Devilops)*

In [115]:
import pandas as pd
import numpy as np

df_ag = pd.read_csv('/content/Agri Data update.csv')
df_ag.head()

,Date,District,Market,Crop Type,Soil Type,Soil pH,Soil Quality,Irrigation Method,Water Consumption (liters/hectare),Water Availability (liters/hectare),Temperature,Humidity,Wind_Speed,N,P,K,Crop Yield,Price (INR/quintal)
0,01-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,11609.330,11335.920,9.440599,80.00000,10.956710,60.5,45.0,31.5,107.97200,2785.953
1,02-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,66.66667,Drip Irrigation,12648.410,12091.900,20.052580,79.94742,8.591577,84.0,66.0,50.0,104.87130,2311.234
2,03-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Canal Irrigation,10063.160,9810.943,12.143100,80.00000,7.227751,71.5,54.0,38.5,26.35612,2353.253
3,04-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,35.00000,Sprinkler Irrigation,10110.540,10754.220,19.751850,80.00000,2.682683,50.0,40.0,30.0,58.93980,2531.584
4,05-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.16667,Canal Irrigation,9320.451,8695.538,16.110390,80.00000,7.696070,49.5,45.0,38.5,32.97041,2314.490

In [116]:
df_ag['Date'] = pd.to_datetime(df_ag['Date'], format='%d-%m-%Y')

In [10]:
df_ag.isnull().sum()

Date                                   0
District                               0
Market                                 0
Crop Type                              0
Soil Type                              0
Soil pH                                0
Soil Quality                           0
Irrigation Method                      0
Water Consumption (liters/hectare)     0
Water Availability (liters/hectare)    0
Temperature                            0
Humidity                               0
Wind_Speed                             0
N                                      0
P                                      0
K                                      0
Crop Yield                             0
Price (INR/quintal)                    0
Unnamed: 18                            0
dtype: int64

In [117]:
df_ag['Crop Yield'].fillna(df_ag['Crop Yield'].median(), inplace=True)

/tmp/ipython-input-3852814784.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [20]:
#df_ag.dropna()

In [19]:
df_ag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2921 entries, 0 to 2920
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Date                                 2920 non-null   object
 1   District                             2920 non-null   object
 2   Market                               2920 non-null   object
 3   Crop Type                            2920 non-null   object
 4   Soil Type                            2920 non-null   object
 5   Soil pH                              2920 non-null   float64
 6   Soil Quality                         2920 non-null   float64
 7   Irrigation Method                    2920 non-null   object
 8   Water Consumption (liters/hectare)   2920 non-null   float64
 9   Water Availability (liters/hectare)  2920 non-null   float64
 10  Temperature                          2920 non-null   float64
 11  Humidity                             2920 non-null   float64
 12  Wind_Speed                           2920 non-null   float64
 13  N                                    2920 non-null   float64
 14  P                                    2920 non-null   float64
 15  K                                    2920 non-null   float64
 16  Crop Yield                           2921 non-null   float64
 17  Price (INR/quintal)                  2920 non-null   float64
 18  Unnamed: 18                          0 non-null      float64
dtypes: float64(13), object(6)
memory usage: 433.7+ KB

In [21]:
df_ag.columns

Index(['Date', 'District', 'Market', 'Crop Type', 'Soil Type', 'Soil pH',
       'Soil Quality', 'Irrigation Method',
       'Water Consumption (liters/hectare)',
       'Water Availability (liters/hectare)', 'Temperature', 'Humidity',
       'Wind_Speed', 'N', 'P', 'K', 'Crop Yield', 'Price (INR/quintal)',
       'Unnamed: 18'],
      dtype='object')

In [22]:
corr_features = [
    'Soil pH',
       'Soil Quality', 'Temperature', 'Humidity',
       'Water Consumption (liters/hectare)',
       'Water Availability (liters/hectare)', 'Temperature', 'Humidity',
       'Wind_Speed', 'N', 'P', 'K', 'Crop Yield', 'Price (INR/quintal)'
]

import plotly.express as px
import plotly.graph_objects as go

# Calculate correlation matrix again
corr_matrix = df_ag[corr_features].corr()

# Select only correlations with target column
target_corr = corr_matrix[['Price (INR/quintal)']].drop(index='Price (INR/quintal)').reset_index()
target_corr.columns = ['Feature', 'Correlation']
target_corr['AbsCorrelation'] = target_corr['Correlation'].abs()

# Sort by absolute correlation
target_corr = target_corr.sort_values(by='AbsCorrelation', ascending=False)

fig = px.bar(
    target_corr,
    x='Feature',
    y='Correlation',
    color='Correlation',
    title='Feature Correlations with Cotton Prices',
    color_continuous_scale='Tealgrn',
    text=target_corr['Correlation'].round(3)
)

fig.update_layout(
    width=900,
    height=650,
    xaxis_title='Feature',
    yaxis_title='Correlation with Cotton Prices',
    bargap=0.3
)

fig.update_traces(
    textposition='outside'
)

fig.show()

In [23]:
df_ag.District.unique()

array(['Ajmer', 'Alwar', nan], dtype=object)

In [24]:
df_ag.Market.unique()

array(['Ajmer APMC Mandi', 'Kishangarh Mandi', 'Alwar APMC Mandi',
       'Tijara Mandi', nan], dtype=object)

In [26]:
df_ag['Crop Type'].unique()

array(['Cotton', nan], dtype=object)

In [118]:
df_cotton_ajmer = df_ag[(df_ag['Crop Type'] == 'Cotton') & (df_ag['District'] == 'Ajmer')]

In [34]:
df_cotton_ajmer.head()

,Date,District,Market,Crop Type,Soil Type,Soil pH,Soil Quality,Irrigation Method,Water Consumption (liters/hectare),Water Availability (liters/hectare),Temperature,Humidity,Wind_Speed,N,P,K,Crop Yield,Price (INR/quintal),Unnamed: 18
0,01-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,11609.330,11335.920,9.440599,80.00000,10.956710,60.5,45.0,31.5,107.97200,2785.953,NaN
1,02-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,66.66667,Drip Irrigation,12648.410,12091.900,20.052580,79.94742,8.591577,84.0,66.0,50.0,104.87130,2311.234,NaN
2,03-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Canal Irrigation,10063.160,9810.943,12.143100,80.00000,7.227751,71.5,54.0,38.5,26.35612,2353.253,NaN
3,04-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,35.00000,Sprinkler Irrigation,10110.540,10754.220,19.751850,80.00000,2.682683,50.0,40.0,30.0,58.93980,2531.584,NaN
4,05-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.16667,Canal Irrigation,9320.451,8695.538,16.110390,80.00000,7.696070,49.5,45.0,38.5,32.97041,2314.490,NaN

### ***Ajmer APMC Mandi Forecasting***

In [119]:
df_cotton_ajmer_forecast = df_cotton_ajmer[
    (df_cotton_ajmer['Crop Type'] == 'Cotton') &
    (df_cotton_ajmer['District'] == 'Ajmer') &
    (df_cotton_ajmer['Market'] == 'Ajmer APMC Mandi')
].copy()

In [65]:
df_cotton_ajmer_forecast.head(14)

,Date,District,Market,Crop Type,Soil Type,Soil pH,Soil Quality,Irrigation Method,Water Consumption (liters/hectare),Water Availability (liters/hectare),Temperature,Humidity,Wind_Speed,N,P,K,Crop Yield,Price (INR/quintal),Unnamed: 18
0,01-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,11609.330,11335.920,9.440599,80.00000,10.956710,60.5,45.0,31.5,107.972000,2785.953,NaN
1,02-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,66.66667,Drip Irrigation,12648.410,12091.900,20.052580,79.94742,8.591577,84.0,66.0,50.0,104.871300,2311.234,NaN
2,03-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Canal Irrigation,10063.160,9810.943,12.143100,80.00000,7.227751,71.5,54.0,38.5,26.356120,2353.253,NaN
3,04-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,35.00000,Sprinkler Irrigation,10110.540,10754.220,19.751850,80.00000,2.682683,50.0,40.0,30.0,58.939800,2531.584,NaN
4,05-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.16667,Canal Irrigation,9320.451,8695.538,16.110390,80.00000,7.696070,49.5,45.0,38.5,32.970410,2314.490,NaN
5,06-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,39.37500,Tube Well,13707.250,13088.410,14.826740,80.00000,10.366660,55.0,44.0,36.0,29.356120,2290.791,NaN
6,07-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Saline,8.00,17.04167,Tube Well,6419.277,6685.758,13.533000,80.00000,9.910484,84.5,66.0,54.0,59.259564,2341.325,NaN
7,08-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Clay,6.25,42.29167,Tube Well,9289.884,9468.516,18.323270,80.00000,8.198084,60.0,45.0,40.0,22.221380,2468.961,NaN
8,09-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,6437.160,6909.588,18.895960,80.00000,6.696707,60.5,45.0,31.5,54.259730,2353.129,NaN
9,10-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,63.66667,Tube Well,15661.880,16224.040,16.865590,80.00000,9.311649,70.0,66.0,55.0,68.119250,1905.749,NaN
10,11-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Sprinkler Irrigation,10553.030,9809.797,16.044320,80.00000,4.120990,60.5,45.0,31.5,28.723530,2119.305,NaN
11,12-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Clay,6.25,48.70833,Canal Irrigation,9733.309,9502.634,15.984310,80.00000,10.655910,72.0,55.0,40.0,51.656270,2145.930,NaN
12,13-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Sprinkler Irrigation,7811.487,8738.674,14.421760,80.00000,9.096689,71.5,54.0,38.5,36.753480,2040.916,NaN
13,14-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Saline,8.00,13.75000,Sprinkler Irrigation,6562.790,6767.839,11.400780,80.00000,11.382450,65.0,55.0,45.0,8.159006,2348.673,NaN

In [120]:
#df_cotton_ajmer_forecast['ds'] = pd.to_datetime(df_cotton_ajmer_forecast['Date'], format="%d-%m-%Y", dayfirst=True )
df_cotton_ajmer_forecast['ds'] = pd.to_datetime(df_cotton_ajmer_forecast['Date'])
df_cotton_ajmer_forecast['y'] = df_cotton_ajmer_forecast['Price (INR/quintal)']

In [50]:
#regressors = [col for col in regressors if col in df_cotton_ajmer_forecast.columns]

In [121]:
from prophet import Prophet

# Make sure regressors list is valid
regressors = ['Soil pH','Soil Quality','Water Consumption (liters/hectare)','Water Availability (liters/hectare)', 'Temperature', 'Humidity','Wind_Speed', 'N', 'P', 'K', 'Crop Yield']

m = Prophet()

# Add all numeric regressors
for reg in regressors:
    m.add_regressor(reg)

# Fit model (must include ALL regressor columns)
m.fit(df_cotton_ajmer_forecast[['ds', 'y'] + regressors])

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

In [122]:
future = m.make_future_dataframe(periods=15)   #  days forecast

# Add regressors to the future frame
for reg in regressors:
    future[reg] = df_cotton_ajmer_forecast[reg].iloc[-1]      # using last value


forecast = m.predict(future)

In [123]:
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

            ds         yhat   yhat_lower   yhat_upper
0   2014-01-01  2430.361018  2037.400932  2810.824455
1   2014-01-02  2464.405042  2098.233867  2838.316046
2   2014-01-03  2504.866623  2108.201958  2915.808212
3   2014-01-04  2455.127372  2064.858519  2843.066381
4   2014-01-05  2473.062493  2099.936812  2870.721450
..         ...          ...          ...          ...
740 2016-01-11  2478.412003  2079.710356  2851.102347
741 2016-01-12  2507.186705  2104.764061  2874.036631
742 2016-01-13  2435.522624  2076.417978  2824.001312
743 2016-01-14  2469.828877  2083.135806  2844.103641
744 2016-01-15  2510.552688  2121.537304  2881.772462

[745 rows x 4 columns]

In [111]:
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,Crop Yield,Crop Yield_lower,Crop Yield_upper,Humidity,...,extra_regressors_additive,extra_regressors_additive_lower,extra_regressors_additive_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2014-01-01,2495.144032,2047.402651,2829.167033,2495.144032,2495.144032,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,-41.835738,-41.835738,-41.835738,0.0,0.0,0.0,2430.361018
1,2014-01-02,2494.930809,2077.179903,2849.401808,2494.930809,2494.930809,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,-7.578491,-7.578491,-7.578491,0.0,0.0,0.0,2464.405042
2,2014-01-03,2494.717586,2142.789349,2874.908560,2494.717586,2494.717586,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,33.096312,33.096312,33.096312,0.0,0.0,0.0,2504.866623
3,2014-01-04,2494.504364,2060.150385,2824.554133,2494.504364,2494.504364,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,-16.429716,-16.429716,-16.429716,0.0,0.0,0.0,2455.127372
4,2014-01-05,2494.291141,2087.021259,2825.363437,2494.291141,2494.291141,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,1.718627,1.718627,1.718627,0.0,0.0,0.0,2473.062493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,2016-01-11,2500.207623,2107.945724,2845.627798,2500.177455,2500.240044,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,1.151656,1.151656,1.151656,0.0,0.0,0.0,2478.412003
741,2016-01-12,2500.256630,2166.502481,2884.316678,2500.217203,2500.298620,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,29.877350,29.877350,29.877350,0.0,0.0,0.0,2507.186705
742,2016-01-13,2500.305637,2066.631486,2828.873245,2500.254804,2500.360030,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,-41.835738,-41.835738,-41.835738,0.0,0.0,0.0,2435.522624
743,2016-01-14,2500.354644,2093.640562,2886.715997,2500.290801,2500.423156,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,-7.578491,-7.578491,-7.578491,0.0,0.0,0.0,2469.828877
744,2016-01-15,2500.403651,2127.629325,2881.478788,2500.329439,2500.493050,-13.219545,-13.219545,-13.219545,-8.471486,...,-22.947276,-22.947276,-22.947276,33.096312,33.096312,33.096312,0.0,0.0,0.0,2510.552688

In [124]:
from sklearn.metrics import mean_absolute_percentage_error

y_true = df_cotton_ajmer_forecast['Price (INR/quintal)'][-730:]
y_pred = forecast['yhat'][:730]

mape = mean_absolute_percentage_error(y_true, y_pred)
print(f"MAPE for Cotton Prices for Ajmer APMC Mandi in Ajmer district : {mape * 100:.2f}%")

MAPE for Cotton Prices for Ajmer APMC Mandi in Ajmer district : 9.94%

In [125]:
forecast_slice = forecast.iloc[0:744][['ds', 'yhat']].copy()

# Rename columns to match your dataframe
forecast_slice = forecast_slice.rename(columns={
    'ds': 'Date',
    'yhat': 'Forecasted_Price'
})


 #Append selected forecast slice
df_cotton_ajmer_forecast = pd.concat([df_cotton_ajmer_forecast, forecast_slice], ignore_index=True)

# Sort by date if needed
#df_cotton_ajmer_forecast = df_cotton_ajmer_forecast.sort_values('Date').reset_index(drop=True)
df_cotton_ajmer_forecast['Date'] = pd.to_datetime(df_cotton_ajmer_forecast['Date'], format='%d-%m-%Y')

In [127]:
df_cotton_ajmer_forecast.drop(columns=['ds','y','Price (INR/quintal)'], inplace=True)

In [128]:
df_cotton_ajmer_forecast.columns

Index(['Date', 'District', 'Market', 'Crop Type', 'Soil Type', 'Soil pH',
       'Soil Quality', 'Irrigation Method',
       'Water Consumption (liters/hectare)',
       'Water Availability (liters/hectare)', 'Temperature', 'Humidity',
       'Wind_Speed', 'N', 'P', 'K', 'Crop Yield', 'Forecasted_Price'],
      dtype='object')

In [132]:

df_cotton_ajmer_forecast['District'].fillna(df_cotton_ajmer_forecast['District'].mode(), inplace=True)
df_cotton_ajmer_forecast['Market'].fillna(df_cotton_ajmer_forecast['Market'].mode(), inplace=True)
df_cotton_ajmer_forecast['Crop Type'].fillna(df_cotton_ajmer_forecast['Crop Type'].mode(), inplace=True)
df_cotton_ajmer_forecast['Soil pH'].fillna(df_cotton_ajmer_forecast['Soil pH'].median(), inplace=True)
df_cotton_ajmer_forecast['Soil Quality'].fillna(df_cotton_ajmer_forecast['Soil Quality'].median(), inplace=True)
df_cotton_ajmer_forecast['Irrigation Method'].fillna(df_cotton_ajmer_forecast['Irrigation Method'].mode(), inplace=True)
df_cotton_ajmer_forecast['Water Consumption (liters/hectare)'].fillna(df_cotton_ajmer_forecast['Water Consumption (liters/hectare)'].median(), inplace=True)
df_cotton_ajmer_forecast['Water Availability (liters/hectare)'].fillna(df_cotton_ajmer_forecast['Water Availability (liters/hectare)'].median(), inplace=True)
df_cotton_ajmer_forecast['Temperature'].fillna(df_cotton_ajmer_forecast['Temperature'].median(), inplace=True)
df_cotton_ajmer_forecast['Humidity'].fillna(df_cotton_ajmer_forecast['Humidity'].median(), inplace=True)
df_cotton_ajmer_forecast['Wind_Speed'].fillna(df_cotton_ajmer_forecast['Wind_Speed'].median(), inplace=True)
df_cotton_ajmer_forecast['Soil Type'].fillna(df_cotton_ajmer_forecast['Soil Type'].mode(), inplace=True)
df_cotton_ajmer_forecast['N'].fillna(df_cotton_ajmer_forecast['N'].median(), inplace=True)
df_cotton_ajmer_forecast['P'].fillna(df_cotton_ajmer_forecast['P'].median(), inplace=True)
df_cotton_ajmer_forecast['K'].fillna(df_cotton_ajmer_forecast['K'].median(), inplace=True)
df_cotton_ajmer_forecast['Crop Yield'].fillna(df_cotton_ajmer_forecast['Crop Yield'].median(), inplace=True)

/tmp/ipython-input-3109608606.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:3: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:4: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:6: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:7: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:8: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:9: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:10: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:11: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:12: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:13: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:14: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:15: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipython-input-3109608606.py:16: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [136]:
df_cotton_ajmer_forecast.head()

,Date,District,Market,Crop Type,Soil Type,Soil pH,Soil Quality,Irrigation Method,Water Consumption (liters/hectare),Water Availability (liters/hectare),Temperature,Humidity,Wind_Speed,N,P,K,Crop Yield,Forecasted_Price
0,2014-01-01,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,11609.330,11335.920,9.440599,80.00000,10.956710,60.5,45.0,31.5,107.97200,NaN
1,2014-01-02,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,66.66667,Drip Irrigation,12648.410,12091.900,20.052580,79.94742,8.591577,84.0,66.0,50.0,104.87130,NaN
2,2014-01-03,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Canal Irrigation,10063.160,9810.943,12.143100,80.00000,7.227751,71.5,54.0,38.5,26.35612,NaN
3,2014-01-04,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,35.00000,Sprinkler Irrigation,10110.540,10754.220,19.751850,80.00000,2.682683,50.0,40.0,30.0,58.93980,NaN
4,2014-01-05,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.16667,Canal Irrigation,9320.451,8695.538,16.110390,80.00000,7.696070,49.5,45.0,38.5,32.97041,NaN

### ***Kishangarh Mandi Forecasting***

In [137]:
df_cotton_ajmer_forecast_new = df_cotton_ajmer[
    (df_cotton_ajmer['Crop Type'] == 'Cotton') &
    (df_cotton_ajmer['District'] == 'Ajmer') &
    (df_cotton_ajmer['Market'] == 'Kishangarh Mandi')
].copy()

In [138]:
df_cotton_ajmer_forecast_new['ds'] = pd.to_datetime(df_cotton_ajmer_forecast_new['Date'])
df_cotton_ajmer_forecast_new['y'] = df_cotton_ajmer_forecast_new['Price (INR/quintal)']

In [139]:
from prophet import Prophet

# Make sure regressors list is valid
regressors = ['Soil pH','Soil Quality','Water Consumption (liters/hectare)','Water Availability (liters/hectare)', 'Temperature', 'Humidity','Wind_Speed', 'N', 'P', 'K', 'Crop Yield']

m = Prophet()

# Add all numeric regressors
for reg in regressors:
    m.add_regressor(reg)

# Fit model (must include ALL regressor columns)
m.fit(df_cotton_ajmer_forecast_new[['ds', 'y'] + regressors])

future = m.make_future_dataframe(periods=15)   #  days forecast

# Add regressors to the future frame
for reg in regressors:
    future[reg] = df_cotton_ajmer_forecast_new[reg].iloc[-1]      # using last value


forecast = m.predict(future)

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

In [140]:
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

            ds         yhat   yhat_lower   yhat_upper
0   2014-01-01  2452.027585  2070.054855  2827.659284
1   2014-01-02  2380.383141  2006.251454  2761.487875
2   2014-01-03  2437.900846  2055.615379  2810.902694
3   2014-01-04  2419.563176  2053.904439  2782.744611
4   2014-01-05  2407.754716  2047.777616  2759.198959
..         ...          ...          ...          ...
740 2016-01-11  2519.408221  2138.827303  2898.036945
741 2016-01-12  2506.530077  2122.864858  2864.106770
742 2016-01-13  2552.866311  2194.955676  2940.569029
743 2016-01-14  2481.087405  2110.125096  2829.693942
744 2016-01-15  2538.470649  2143.614150  2909.200778

[745 rows x 4 columns]

In [141]:
from sklearn.metrics import mean_absolute_percentage_error

y_true = df_cotton_ajmer_forecast_new['Price (INR/quintal)'][-730:]
y_pred = forecast['yhat'][:730]

mape = mean_absolute_percentage_error(y_true, y_pred)
print(f"MAPE for Cotton Prices for Kishangarh Mandi in Ajmer district : {mape * 100:.2f}%")

MAPE for Cotton Prices for Kishangarh Mandi in Ajmer district : 9.40%

In [142]:
forecast_slice = forecast.iloc[0:744][['ds', 'yhat']].copy()

# Rename columns to match your dataframe
forecast_slice = forecast_slice.rename(columns={
    'ds': 'Date',
    'yhat': 'Forecasted_Price'
})


 #Append selected forecast slice
df_cotton_ajmer_forecast_new = pd.concat([df_cotton_ajmer_forecast_new, forecast_slice], ignore_index=True)

# Sort by date if needed
#df_cotton_ajmer_forecast = df_cotton_ajmer_forecast.sort_values('Date').reset_index(drop=True)
df_cotton_ajmer_forecast_new['Date'] = pd.to_datetime(df_cotton_ajmer_forecast_new['Date'], format='%d-%m-%Y')

In [143]:
df_cotton_ajmer_forecast_new.drop(columns=['ds','y','Price (INR/quintal)'], inplace=True)

In [144]:
df_cotton_ajmer_forecast.to_csv('ajmer_forecast.csv', index=False)

In [145]:
df_cotton_ajmer_forecast_new.to_csv('ajmer_forecast_new.csv', index=False)

## **Forecasted Prices Testing**

In [146]:
import pandas as pd


df = pd.read_csv('/content/Merge agri data.csv')
df

,Date,District,Market,Crop Type,Soil Type,Soil pH,Soil Quality,Irrigation Method,Water Consumption (liters/hectare),Water Availability (liters/hectare),Temperature,Humidity,Wind_Speed,N,P,K,Crop Yield,Forecasted_Price
0,01-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.83333,Tube Well,11609.330,11335.920,9.440599,80.00000,10.956710,60.5,45.0,31.5,107.97200,2785.953000
1,02-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Loamy,6.50,66.66667,Drip Irrigation,12648.410,12091.900,20.052580,79.94742,8.591577,84.0,66.0,50.0,104.87130,2311.234000
2,03-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,27.33333,Canal Irrigation,10063.160,9810.943,12.143100,80.00000,7.227751,71.5,54.0,38.5,26.35612,2353.253000
3,04-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Sandy,6.75,35.00000,Sprinkler Irrigation,10110.540,10754.220,19.751850,80.00000,2.682683,50.0,40.0,30.0,58.93980,2531.584000
4,05-01-2014,Ajmer,Ajmer APMC Mandi,Cotton,Peaty,5.50,22.16667,Canal Irrigation,9320.451,8695.538,16.110390,80.00000,7.696070,49.5,45.0,38.5,32.97041,2314.490000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2943,10-01-2016,Ajmer,Kishangarh Mandi,Cotton,Peaty,5.50,23.83333,Sprinkler Irrigation,11498.960,11376.280,27.283440,72.71656,8.555618,55.0,49.5,38.5,12.95149,2507.725712
2944,11-01-2016,Ajmer,Kishangarh Mandi,Cotton,Peaty,5.50,23.83333,Sprinkler Irrigation,11498.960,11376.280,27.283440,72.71656,8.555618,55.0,49.5,38.5,12.95149,2519.408221
2945,12-01-2016,Ajmer,Kishangarh Mandi,Cotton,Peaty,5.50,23.83333,Sprinkler Irrigation,11498.960,11376.280,27.283440,72.71656,8.555618,55.0,49.5,38.5,12.95149,2506.530077
2946,13-01-2016,Ajmer,Kishangarh Mandi,Cotton,Peaty,5.50,23.83333,Sprinkler Irrigation,11498.960,11376.280,27.283440,72.71656,8.555618,55.0,49.5,38.5,12.95149,2552.866311
2947,14-01-2016,Ajmer,Kishangarh Mandi,Cotton,Peaty,5.50,23.83333,Sprinkler Irrigation,11498.960,11376.280,27.283440,72.71656,8.555618,55.0,49.5,38.5,12.95149,2481.087405

In [167]:
import pandas as pd
from ipywidgets import interact_manual, Dropdown, Text
from IPython.display import display

# Ensure Date is datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

def display_7day_forecast(crop, district, start_date_str):
    try:
        start_date = pd.to_datetime(start_date_str)
    except:
        print("❌ Invalid date format — use YYYY-MM-DD")
        return

    end_date = start_date + pd.Timedelta(days=7)

    # Filter dataframe
    filtered_df = df[
        (df['Crop Type'] == crop) &
        (df['District'] == district) &
        (df['Date'] >= start_date) &
        (df['Date'] <= end_date)
    ]

    if filtered_df.empty:
        print("⚠ No forecast data available for this selection / date range.")
        return

    # Drop duplicates for Date + Market to avoid repeated rows
    filtered_df = filtered_df.drop_duplicates(subset=['Date', 'Market'])

    # Sort by Date and Market
    filtered_df = filtered_df.sort_values(['Date', 'Market']).reset_index(drop=True)

    # Display only relevant columns
    display(filtered_df[['Date', 'Market', 'Forecasted_Price']])

# Dropdowns
crop_dropdown = Dropdown(
    options=sorted(df['Crop Type'].unique()),
    description='Crop:'
)

district_dropdown = Dropdown(
    options=sorted(df['District'].unique()),
    description='District:'
)

date_input = Text(
    value='2014-01-01',
    description='Start Date (YYYY-MM-DD):'
)

# Run button
interact_manual(display_7day_forecast, crop=crop_dropdown, district=district_dropdown, start_date_str=date_input)

interactive(children=(Dropdown(description='Crop:', options=('Cotton',), value='Cotton'), Dropdown(description…

## **Gradio Deployment**

In [170]:
import pandas as pd
import gradio as gr

# Ensure Date column is datetime
#df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

def display_7day_forecast_gradio(crop, district, start_date_str):
    try:
        start_date = pd.to_datetime(start_date_str)
    except:
        return "❌ Invalid date format — use YYYY-MM-DD"

    end_date = start_date + pd.Timedelta(days=7)

    # Filter dataframe
    filtered_df = df[
        (df['Crop Type'] == crop) &
        (df['District'] == district) &
        (df['Date'] >= start_date) &
        (df['Date'] <= end_date)
    ]

    if filtered_df.empty:
        return "⚠ No forecast data available for this selection / date range."

    # Drop duplicates and sort
    filtered_df = filtered_df.drop_duplicates(subset=['Date', 'Market'])
    filtered_df = filtered_df.sort_values(['Date', 'Market']).reset_index(drop=True)

    # Return relevant columns
    return filtered_df[['Date', 'Market', 'Forecasted_Price']]

# Gradio Interface
crop_list = sorted(df['Crop Type'].unique())
district_list = sorted(df['District'].unique())

iface = gr.Interface(
    fn=display_7day_forecast_gradio,
    inputs=[
        gr.Dropdown(choices=crop_list, label="Crop"),
        gr.Dropdown(choices=district_list, label="District"),
        gr.Textbox(value="2014-01-01", label="Start Date (YYYY-MM-DD)")
    ],
    outputs="dataframe",
    title="7-Day Forecast Table",
    description="Select Crop and District, enter a start date, and see the next 7 days forecasted prices."
)

iface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://8aa4fd9bd1916486fa.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

### **What's Next ?**

* Gradio Deployment

* LLM Integration :- Best selling price suggestions using AI

**How it will work utlizing LLM ?** - *Farmers maximize profits and sell smart. Farmers select their crop, state, and district, and enter a start date. The platform then displays interactive 7- or 15-day price forecasts across all nearby markets. An AI-powered LLM analyzes these forecasts and recommends the best market(s) to sell, helping farmers make data-driven decisions, reduce reliance on middlemen, and secure fair, optimized prices for their produce.*


Also more enhancement for dataset to make it more Proactive Prototype (which will be and scalable solution).